### ISSUE TITLE
Copyright violations

### ISSUE THREAD

**Issue by UncleRus** [kairos-dev/kairos-core#2]
Some source texts in this project are taken from esp-idf-lib, and, unfortunately, are taken illegally: header comments containing texts of licenses and authors of the source code have been removed from them. I demand that you either restore the header comments as it was done in the original repository, or refuse to use them.

**Comment by arturgoms** [comment]
Sorry for that, i'll add again in the future.

**Comment by UncleRus** [comment]
Is this future already here? How long do I have to wait for legal requirements to be met?

**Comment by UncleRus** [comment]
And I would prefer that you not close this issue until the problem is fixed.

**Comment by UncleRus** [comment]
Thank you!
